# 本地开发覆盖配置示例，根据需要调整后重命名或直接引用。
app:
  env: development
  debug: true

postgres:
  dsn: postgresql://postgres:123456@192.168.0.119:5432/semantic_forge_local
  schema: rdf_acl
  migrations_table: rdf_acl_migrations

rdf:
  endpoint: http://192.168.0.119:3030
  dataset: semantic_forge_test



