# 本地开发覆盖配置模板（提交到仓库，无敏感信息）
# 复制为 config/local.yaml 后按需修改，本地文件会被 .gitignore 忽略。

app:
  env: development
  debug: true
  # 如需覆盖端口可解除注释
  # port: 8000

rdf:
  endpoint: http://localhost:3030
  dataset: semantic_forge_test

postgres:
  dsn: postgresql://postgres:password@localhost:5432/semantic_forge
  schema: rdf_acl
  migrations_table: rdf_acl_migrations

redis:
  url: redis://:password@localhost:6379/0
  namespace: semanticforge

qdrant:
  http_url: http://localhost:6333
  grpc_url: grpc://localhost:6334

logging:
  level: DEBUG

