rdf:
  endpoint: http://192.168.0.119:3030
  dataset: semantic_forge_test

postgres:
  dsn: postgresql+psycopg://postgres:123456@192.168.0.119:5432/postgres
  schema: rdf_acl
  migrations_table: rdf_acl_migrations

